# SELECT THE IMAGE
FROM python:3.10

# SET THE WORKING DIRECTORY
WORKDIR /app

# COPY ALL THE FILES INTO THE WORKING DIRECTORY
COPY . /app

# INSTALL THE DEPENDENCIES
RUN pip install -r requirements.txt

# RUN THE main.py FILE
ENTRYPOINT ["python3.10"]
CMD ["main.py"]