# SELECT THE IMAGE
FROM python:3.10-alpine3.20

# SET THE WORKING DIRECTORY
WORKDIR /app

# COPY ALL THE FILES INTO THE WORKING DIRECTORY
COPY . /app

# INSTALL THE CURRENT PACKAGE AND ITS DEPENDENCIES
RUN pip install -e .

# START THE FLASK APP
ENTRYPOINT ["flask", "run"]